[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["cd backend && npm install"]

[phases.build]  
cmds = ["cd backend && echo \"Backend build complete\""]

[start]
cmd = "cd backend && npm start"
